"""courses

Revision ID: 28a06f96c3ce
Revises: 2cfba21cd66f
Create Date: 2026-07-22 16:50:27.065537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28a06f96c3ce'
down_revision = '2cfba21cd66f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=True),
    sa.Column('level', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('title_mn', sa.String(length=200), nullable=False),
    sa.Column('title_en', sa.String(length=200), nullable=True),
    sa.Column('tagline_mn', sa.String(length=300), nullable=True),
    sa.Column('tagline_en', sa.String(length=300), nullable=True),
    sa.Column('age_min', sa.Integer(), nullable=True),
    sa.Column('age_max', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('duration_weeks', sa.Integer(), nullable=True),
    sa.Column('format', sa.String(length=20), nullable=True),
    sa.Column('price_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('discount_percent', sa.Integer(), nullable=True),
    sa.Column('banner_image_url', sa.String(length=500), nullable=True),
    sa.Column('icon', sa.String(length=120), nullable=True),
    sa.Column('description_mn', sa.Text(), nullable=True),
    sa.Column('description_en', sa.Text(), nullable=True),
    sa.Column('prerequisites_mn', sa.Text(), nullable=True),
    sa.Column('prerequisites_en', sa.Text(), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('final_project_type', sa.String(length=60), nullable=True),
    sa.Column('curriculum', sa.JSON(), nullable=True),
    sa.Column('whats_included', sa.JSON(), nullable=True),
    sa.Column('instructors', sa.JSON(), nullable=True),
    sa.Column('cert_template_key', sa.String(length=500), nullable=True),
    sa.Column('cert_template_name', sa.String(length=255), nullable=True),
    sa.Column('contract_template_key', sa.String(length=500), nullable=True),
    sa.Column('contract_template_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_courses_slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_courses_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_courses_status'))
        batch_op.drop_index(batch_op.f('ix_courses_slug'))

    op.drop_table('courses')
    # ### end Alembic commands ###
