"""Learning surface for the mobile app: modules, lessons, materials, progress,
notes, assignments + submissions + student files, quizzes + attempts, certificates,
password-reset codes, class sessions + attendance, push tokens, notifications.

Tables only; existing tables are untouched. Names follow the ERD.

Revision ID: 2a7c0f6b1ac3
Revises: c1d4f2a70b83
Create Date: 2026-09-28 19:01:16.698878

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = '2a7c0f6b1ac3'
down_revision = 'c1d4f2a70b83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('name_mn', sa.String(length=200), nullable=False),
    sa.Column('name_en', sa.String(length=200), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('course_topics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_course_topics_course_id'), ['course_id'], unique=False)

    op.create_table('firebase_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=512), nullable=False),
    sa.Column('platform', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['auth_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    with op.batch_alter_table('firebase_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_firebase_tokens_account_id'), ['account_id'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['auth_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index('ix_notifications_account_read', ['account_id', 'read_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_created_at'), ['created_at'], unique=False)

    op.create_table('otp_verifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('purpose', sa.String(length=30), nullable=False),
    sa.Column('code_hash', sa.String(length=128), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['auth_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('otp_verifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_otp_verifications_account_id'), ['account_id'], unique=False)

    op.create_table('student_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('file_key', sa.String(length=500), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=120), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_key')
    )
    with op.batch_alter_table('student_files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_student_files_student_id'), ['student_id'], unique=False)

    op.create_table('class_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cohort_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('session_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.String(length=5), nullable=True),
    sa.Column('end_time', sa.String(length=5), nullable=True),
    sa.Column('qr_token_hash', sa.String(length=64), nullable=True),
    sa.Column('qr_expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cohort_id'], ['cohorts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['course_topics.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cohort_id', 'session_date', 'start_time', name='uq_class_session_slot')
    )
    with op.batch_alter_table('class_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_class_sessions_cohort_id'), ['cohort_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_class_sessions_qr_token_hash'), ['qr_token_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_class_sessions_session_date'), ['session_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_class_sessions_topic_id'), ['topic_id'], unique=False)

    op.create_table('course_lessons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('name_mn', sa.String(length=200), nullable=False),
    sa.Column('name_en', sa.String(length=200), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('classroom_embed_url', sa.String(length=500), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('summary_mn', sa.Text(), nullable=True),
    sa.Column('summary_en', sa.Text(), nullable=True),
    sa.Column('sections', sa.JSON(), nullable=True),
    sa.Column('is_preview', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['course_topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('course_lessons', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_course_lessons_topic_id'), ['topic_id'], unique=False)

    op.create_table('attendance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_session_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('method', sa.String(length=20), nullable=False),
    sa.Column('marked_by_teacher_id', sa.Integer(), nullable=True),
    sa.Column('checked_in_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['class_session_id'], ['class_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['marked_by_teacher_id'], ['teachers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('class_session_id', 'student_id', name='uq_attendance')
    )
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attendance_class_session_id'), ['class_session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendance_student_id'), ['student_id'], unique=False)

    op.create_table('certificates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('enrollment_id', sa.Integer(), nullable=True),
    sa.Column('cert_number', sa.String(length=40), nullable=False),
    sa.Column('file_key', sa.String(length=500), nullable=True),
    sa.Column('verify_url', sa.String(length=500), nullable=True),
    sa.Column('payment_cleared', sa.Boolean(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('issued_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['enrollment_id'], ['enrollments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cert_number'),
    sa.UniqueConstraint('student_id', 'course_id', name='uq_certificate_student_course')
    )
    with op.batch_alter_table('certificates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_certificates_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_certificates_student_id'), ['student_id'], unique=False)

    op.create_table('exams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('lesson_id', sa.Integer(), nullable=True),
    sa.Column('name_mn', sa.String(length=200), nullable=False),
    sa.Column('name_en', sa.String(length=200), nullable=True),
    sa.Column('pass_percent', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lesson_id'], ['course_lessons.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['topic_id'], ['course_topics.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exams', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exams_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_exams_lesson_id'), ['lesson_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_exams_topic_id'), ['topic_id'], unique=False)

    op.create_table('lesson_materials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('cohort_id', sa.Integer(), nullable=True),
    sa.Column('uploaded_by_account_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=True),
    sa.Column('file_key', sa.String(length=500), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('content_type', sa.String(length=120), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cohort_id'], ['cohorts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lesson_id'], ['course_lessons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_account_id'], ['auth_accounts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lesson_materials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lesson_materials_cohort_id'), ['cohort_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lesson_materials_lesson_id'), ['lesson_id'], unique=False)

    op.create_table('lesson_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['course_lessons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'lesson_id', name='uq_lesson_note')
    )
    with op.batch_alter_table('lesson_notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lesson_notes_lesson_id'), ['lesson_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lesson_notes_student_id'), ['student_id'], unique=False)

    op.create_table('lesson_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enrollment_id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('watched_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['enrollment_id'], ['enrollments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lesson_id'], ['course_lessons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('enrollment_id', 'lesson_id', name='uq_lesson_progress')
    )
    with op.batch_alter_table('lesson_progress', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lesson_progress_enrollment_id'), ['enrollment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lesson_progress_lesson_id'), ['lesson_id'], unique=False)

    op.create_table('assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cohort_id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=True),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.Column('title_mn', sa.String(length=200), nullable=False),
    sa.Column('title_en', sa.String(length=200), nullable=True),
    sa.Column('instructions_mn', sa.Text(), nullable=True),
    sa.Column('instructions_en', sa.Text(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('max_score', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('attachment_material_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['attachment_material_id'], ['lesson_materials.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['cohort_id'], ['cohorts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lesson_id'], ['course_lessons.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assignments_cohort_id'), ['cohort_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assignments_lesson_id'), ['lesson_id'], unique=False)

    op.create_table('exam_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('image', sa.String(length=500), nullable=True),
    sa.Column('point', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exam_questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exam_questions_exam_id'), ['exam_id'], unique=False)

    op.create_table('student_exams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('correct_count', sa.Integer(), nullable=True),
    sa.Column('total', sa.Integer(), nullable=True),
    sa.Column('percent', sa.Integer(), nullable=True),
    sa.Column('is_passed', sa.Boolean(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('student_exams', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_student_exams_exam_id'), ['exam_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_exams_student_id'), ['student_id'], unique=False)
        batch_op.create_index('uq_student_exams_open', ['exam_id', 'student_id'], unique=True, postgresql_where=sa.text('completed_at IS NULL'))

    op.create_table('assignment_submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('submission_url', sa.String(length=1000), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('file_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('score', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('graded_by_teacher_id', sa.Integer(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.Column('graded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['file_id'], ['student_files.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['graded_by_teacher_id'], ['teachers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assignment_id', 'student_id', 'version', name='uq_submission_version')
    )
    with op.batch_alter_table('assignment_submissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assignment_submissions_assignment_id'), ['assignment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assignment_submissions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_assignment_submissions_student_id'), ['student_id'], unique=False)

    op.create_table('exam_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['exam_questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exam_answers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exam_answers_question_id'), ['question_id'], unique=False)

    op.create_table('student_exam_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_exam_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('option_id', sa.Integer(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('answered_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['option_id'], ['exam_answers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['exam_questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_exam_id'], ['student_exams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_exam_id', 'question_id', name='uq_attempt_question')
    )
    with op.batch_alter_table('student_exam_answers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_student_exam_answers_student_exam_id'), ['student_exam_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_exam_answers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_exam_answers_student_exam_id'))

    op.drop_table('student_exam_answers')
    with op.batch_alter_table('exam_answers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exam_answers_question_id'))

    op.drop_table('exam_answers')
    with op.batch_alter_table('assignment_submissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assignment_submissions_student_id'))
        batch_op.drop_index(batch_op.f('ix_assignment_submissions_status'))
        batch_op.drop_index(batch_op.f('ix_assignment_submissions_assignment_id'))

    op.drop_table('assignment_submissions')
    with op.batch_alter_table('student_exams', schema=None) as batch_op:
        batch_op.drop_index('uq_student_exams_open', postgresql_where=sa.text('completed_at IS NULL'))
        batch_op.drop_index(batch_op.f('ix_student_exams_student_id'))
        batch_op.drop_index(batch_op.f('ix_student_exams_exam_id'))

    op.drop_table('student_exams')
    with op.batch_alter_table('exam_questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exam_questions_exam_id'))

    op.drop_table('exam_questions')
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assignments_lesson_id'))
        batch_op.drop_index(batch_op.f('ix_assignments_cohort_id'))

    op.drop_table('assignments')
    with op.batch_alter_table('lesson_progress', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lesson_progress_lesson_id'))
        batch_op.drop_index(batch_op.f('ix_lesson_progress_enrollment_id'))

    op.drop_table('lesson_progress')
    with op.batch_alter_table('lesson_notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lesson_notes_student_id'))
        batch_op.drop_index(batch_op.f('ix_lesson_notes_lesson_id'))

    op.drop_table('lesson_notes')
    with op.batch_alter_table('lesson_materials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lesson_materials_lesson_id'))
        batch_op.drop_index(batch_op.f('ix_lesson_materials_cohort_id'))

    op.drop_table('lesson_materials')
    with op.batch_alter_table('exams', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exams_topic_id'))
        batch_op.drop_index(batch_op.f('ix_exams_lesson_id'))
        batch_op.drop_index(batch_op.f('ix_exams_course_id'))

    op.drop_table('exams')
    with op.batch_alter_table('certificates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_certificates_student_id'))
        batch_op.drop_index(batch_op.f('ix_certificates_course_id'))

    op.drop_table('certificates')
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attendance_student_id'))
        batch_op.drop_index(batch_op.f('ix_attendance_class_session_id'))

    op.drop_table('attendance')
    with op.batch_alter_table('course_lessons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_course_lessons_topic_id'))

    op.drop_table('course_lessons')
    with op.batch_alter_table('class_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_class_sessions_topic_id'))
        batch_op.drop_index(batch_op.f('ix_class_sessions_session_date'))
        batch_op.drop_index(batch_op.f('ix_class_sessions_qr_token_hash'))
        batch_op.drop_index(batch_op.f('ix_class_sessions_cohort_id'))

    op.drop_table('class_sessions')
    with op.batch_alter_table('student_files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_files_student_id'))

    op.drop_table('student_files')
    with op.batch_alter_table('otp_verifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_otp_verifications_account_id'))

    op.drop_table('otp_verifications')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_created_at'))
        batch_op.drop_index('ix_notifications_account_read')

    op.drop_table('notifications')
    with op.batch_alter_table('firebase_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_firebase_tokens_account_id'))

    op.drop_table('firebase_tokens')
    with op.batch_alter_table('course_topics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_course_topics_course_id'))

    op.drop_table('course_topics')
    # ### end Alembic commands ###
