"""classrooms

Revision ID: 32624d56e0b0
Revises: 28a06f96c3ce
Create Date: 2026-07-22 18:27:24.843510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32624d56e0b0'
down_revision = '28a06f96c3ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classrooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('center_name', sa.String(length=200), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('floor', sa.String(length=40), nullable=True),
    sa.Column('equipment', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('center_name', 'name', name='uq_classroom_center_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('classrooms')
    # ### end Alembic commands ###
