"""ERD parity fields (courses/classrooms/cohorts/enrollments)

Revision ID: 4ca0bf002d40
Revises: 67f73436d8aa
Create Date: 2026-07-22 18:56:13.607646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ca0bf002d40'
down_revision = '67f73436d8aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classrooms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.String(length=255), nullable=True))

    with op.batch_alter_table('cohorts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_cohort_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('graduation_date', sa.Date(), nullable=True))
        batch_op.create_index(batch_op.f('ix_cohorts_parent_cohort_id'), ['parent_cohort_id'], unique=False)
        batch_op.create_foreign_key(None, 'cohorts', ['parent_cohort_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('target_audience', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('duration_label', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('sort_order', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('has_exam', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('has_final_project', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('has_attendance', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('attendance_method', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('google_classroom_url', sa.String(length=500), nullable=True))

    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('course_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('progress_pct', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('created_via', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('created_by_admin_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('completed_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_enrollments_course_id'), ['course_id'], unique=False)
        batch_op.create_foreign_key(None, 'courses', ['course_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_enrollments_course_id'))
        batch_op.drop_column('completed_at')
        batch_op.drop_column('created_by_admin_id')
        batch_op.drop_column('created_via')
        batch_op.drop_column('progress_pct')
        batch_op.drop_column('course_id')

    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_column('google_classroom_url')
        batch_op.drop_column('attendance_method')
        batch_op.drop_column('has_attendance')
        batch_op.drop_column('has_final_project')
        batch_op.drop_column('has_exam')
        batch_op.drop_column('sort_order')
        batch_op.drop_column('duration_label')
        batch_op.drop_column('target_audience')

    with op.batch_alter_table('cohorts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_cohorts_parent_cohort_id'))
        batch_op.drop_column('graduation_date')
        batch_op.drop_column('parent_cohort_id')

    with op.batch_alter_table('classrooms', schema=None) as batch_op:
        batch_op.drop_column('location')

    # ### end Alembic commands ###
