"""cohort meeting time (days/start/end)

Revision ID: 4da730ec1a17
Revises: 4ca0bf002d40
Create Date: 2026-07-22 19:19:42.181194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4da730ec1a17'
down_revision = '4ca0bf002d40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cohorts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('meeting_days', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('start_time', sa.String(length=5), nullable=True))
        batch_op.add_column(sa.Column('end_time', sa.String(length=5), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cohorts', schema=None) as batch_op:
        batch_op.drop_column('end_time')
        batch_op.drop_column('start_time')
        batch_op.drop_column('meeting_days')

    # ### end Alembic commands ###
