"""cohorts + enrollments

Revision ID: 67f73436d8aa
Revises: 32624d56e0b0
Create Date: 2026-07-22 18:40:55.282300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67f73436d8aa'
down_revision = '32624d56e0b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cohorts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.Column('classroom_id', sa.Integer(), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('schedule_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['classroom_id'], ['classrooms.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cohorts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cohorts_classroom_id'), ['classroom_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cohorts_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cohorts_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_cohorts_teacher_id'), ['teacher_id'], unique=False)

    op.create_table('enrollments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cohort_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cohort_id'], ['cohorts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cohort_id', 'student_id', name='uq_enrollment_cohort_student')
    )
    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_enrollments_cohort_id'), ['cohort_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_enrollments_student_id'), ['student_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_enrollments_student_id'))
        batch_op.drop_index(batch_op.f('ix_enrollments_cohort_id'))

    op.drop_table('enrollments')
    with op.batch_alter_table('cohorts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cohorts_teacher_id'))
        batch_op.drop_index(batch_op.f('ix_cohorts_status'))
        batch_op.drop_index(batch_op.f('ix_cohorts_course_id'))
        batch_op.drop_index(batch_op.f('ix_cohorts_classroom_id'))

    op.drop_table('cohorts')
    # ### end Alembic commands ###
